#+SETUPFILE: ./0orgsetup.org
#+TITLE: OidaDB File Creation

The first step to the workflow for oidadb starts on the premise of
simple file IO. A single database is stored in a single file. So
creating a database is will intern create a file. And deleting a
database will intern delete said file.

With that being said, to create a new database see [[See Also][odb_create]]. This
will create the file itself (or use an existing file in some cases)
and initialize that file to be a oidadb database.

And to delete a database... well you can just delete the file.

* Contents

 1. [[./odb_create.org][=odb_create=]] - Generating new OidaDB Files
 2. [[./odb_createparams_t.org][=odb_createparams_t=]] - Configuring new OidaDB Files

* The OidaDB File
** Specification
Every single byte that goes from and to OidaDB database will always be
associated to a file. This file, for intents and purposes, /is/ the
database. If you wish to make backups of your database, you'd only
need to copy this database file to a safe destination.
** Lenting
* See Also
 - [[./odb_host.org][=odb_host=]]
 - [[./odb_handle.org][=odb_handle=]]
