#+SETUPFILE: ./0orgsetup.org
#+TITLE: odbh_job, odbh_j* family

* Synopsis

#+BEGIN_SRC c
#include <oidadb/oidadb.h>

odb_err odbh_job   (odbh *handle, odb_jobtype_t jobtype, odb_jobflag_t flags);
odb_err odbh_jwrite(odbh *handle, const void *buf, int bufc);
odb_err odbh_jread (odbh *handle, void *o_buf, int bufc);
odb_err odbh_jclose(odbh *handle,);
#+END_SRC



* Description
The =odbh_job= family of functions are used by the handle install jobs
into the host. For every job that is installed inside the host, a
worker will eventually come by and take ownership of the job and
execute the job to either failure or completion.

Each job installed will open up what is known as a /transfer
buffer/. This transfer buffer is treated like a stream in terms that
it can be read and written too provided that you follow the protocol
specified by the [[See Also][=jobtype=]] (required reading, types & job protocols
not discussed in this chapter).

 - *=odbh_job=* - Install a job denoted by =jobtype= and with
   modifiers [[See Also][=flags=]] into the host to which =handle= has connected
   too. Then return a handle for that job into the output pointer of
   =o_jhandle= if non-errornous.
 - *=odbh_jwrite=* - Set the job (refered to by =jhandle=) to write
   =bufc= bytes of =buf= into the transfer buffer.
 - *=odbh_jread=* - Set the job (refered to by =jhandle=) to read
   =bufc= bytes of the transfer buffer into =o_buf=.
 - *=odbh_jclose=* - Close the job (refered to by =jhandle=). TODO:
   make note about calling this before the initial write will thus
   make the stream unidrectional.

* Errors

 - =ODB_EINVAL= - =jhandle= or =handle= was null
 - =ODB_EINVAL= - (=odbh_jread=/=odbh_jwrite=) buff is null and count is
   not 0.
 - =ODB_ECLOSED= - Call to =odbh_jclose= / =odbh_jread= / =odbh_jwrite= after the stream
   has been marked as closed (either by =odbh_jclose= or otherwise).
 - =ODB_EVERSION= - =jobtype= was not valid or not defined in this library's version
 - =ODB_EOPEN= - (=odbh_job=) Attempt to install another job before
   the completion of the first job.
 - =ODB_EPROTO= - (=odbh_jread=/=odbh_jwrite=) You failed to properly
   follow protocol for the installed =jobtype=.
 - =ODB_EPIPE= - The stream was deliberately broken by the host.
 - =ODB_ECRIT= - The stream was broken for unexpected reasons (such as
   bad network, host no longer responding, ect). The stream will be
   marked as closed.

* Voltility

Depending on the type, the rules of what is atomic and what is not
atomic vary. See [[See Also][odbh_jobtype_t]] for more information.

A single handle may conduct a single job at any given time. If you
wish to execute multiple jobs at once, you may do so via multiple
handles all executing their own jobs. I will remind you though that
every handle must have its own thread. If you attempt to execute
multiple jobs on the same thread you'll run into deadlocks that will
slow down the rest of the database.


* See Also

 - [[./odbh.org][OidaDB Handles]]
 - [[./odb_elm_jobs.org][Jobs]] - A high-level overview of OdbaDB jobs and their life
   cycle. As well as discussion and advise for increasing performance.
 - [[./odbh_jobdesc_t.org][=odbh_jobdesc_t=]] - For specifications on protocols of job
   types. This is required reading to properly use =odbh_jread= and
   =odbh_jwrite=.
 - [[./odbh_jobflags][=odbh_jobflags_t=]] - Optional flags and modifiers for installing
   jobs.
