#+SETUPFILE: ./0orgsetup.org
#+TITLE: odbh_job - Install jobs

* Synopsis

#+BEGIN_SRC c
#include <oidadb/oidadb.h>

odb_err odbh_job(odbh *handle, odb_jobtype_t jobtype, ... /* args */);
#+END_SRC



* Description
The =odbh_job= function is used by the handle install jobs into the
host. For every job that is installed inside the host, a worker will
eventually come by and take ownership of the job and execute the job
to either failure or completion. The job in question is determained by
=jobtype= with parameters you pass in via =args= as documented below

** Common Args

** =ODB_JALLOC (odb_eid, odb_err, odb_oid *, usrobj)= - Create a object
This will create a new object for a given entity. If OidaDB can, it
will reuse something that has previously been deleted. Thus, the
returned oid may be one that has been returned before.

*** Protocol

| Direction  | Name   | Datatype | Notes                                |
|------------+--------+----------+--------------------------------------|
| odbj_write | eid    | odb_eid  | The entity id to create a new object |
| odbj_read  | err    | odb_err  | [[Die-Error]]: See Errors                |
| odbj_read  | oid    | odb_oid  | The OID of the newly created item    |
| odbj_write | object | [[usrobj]]   | The object data itself               |

*** Errors

 - =ODB_ENOENT= - Entity not valid.
 - =ODB_ENOSPACE= - No more space could be allocated for this entity.


* Errors

 - =ODB_EINVAL= - =jhandle= or =handle= was null
 - =ODB_EINVAL= - (=odbh_jread=/=odbh_jwrite=) buff is null and count is
   not 0.
 - =ODB_ECLOSED= - Call to =odbh_jclose= / =odbh_jread= / =odbh_jwrite= after the stream
   has been marked as closed (either by =odbh_jclose= or otherwise).
 - =ODB_EVERSION= - =jobtype= was not valid or not defined in this library's version
 - =ODB_EOPEN= - (=odbh_job=) Attempt to install another job before
   the completion of the first job.
 - =ODB_EPROTO= - (=odbh_jread=/=odbh_jwrite=) You failed to properly
   follow protocol for the installed =jobtype=.
 - =ODB_EPIPE= - The stream was deliberately broken by the host.
 - =ODB_ECRIT= - The stream was broken for unexpected reasons (such as
   bad network, host no longer responding, ect). The stream will be
   marked as closed.

* Voltility

Depending on the type, the rules of what is atomic and what is not
atomic vary. See [[See Also][odbh_jobtype_t]] for more information.

A single handle may conduct a single job at any given time. If you
wish to execute multiple jobs at once, you may do so via multiple
handles all executing their own jobs. I will remind you though that
every handle must have its own thread. If you attempt to execute
multiple jobs on the same thread you'll run into deadlocks that will
slow down the rest of the database.

* See Also

 - [[./odbh.org][OidaDB Handles]]
 - [[./odb_elm_jobs.org][Jobs]] - A high-level overview of OdbaDB jobs and their life
   cycle. As well as discussion and advise for increasing performance.
 - [[./odbh_jobdesc_t.org][=odbh_jobdesc_t=]] - For specifications on protocols of job
   types. This is required reading to properly use =odbh_jread= and
   =odbh_jwrite=.
