#+SETUPFILE: ./0orgsetup.org
#+TITLE: Preface

* About this Book
This book, manual, documentaiton, what ever you want to call it is for
OidaDB. OidaDB is what is known as a proactive database. This database
has many moving parts, and many ways to be configured: some may say
"enough rope to hang yourself".

This manual will provide you everything you could possibly know about
how to use OidaDB. It will also discuss pitfalls and way to take
advantages of it.

This manual is not inclusive of exercises: it will stricktly be
technical documentation. Thus, there will not be anything like a
"quick start guide", as that would be classified as an excersise.
* Manual Version

This manual is for *version 1.0* of oidadb. See [[./versioning.org][Versioning]] for more
detail.

* Audience
This manual is mainly written for those with

 - at least 3 years of experience of software programming in general.
 - at least a year of C experience, equivilent length of experience in
   GoLang, Rust, C++, or other non-virtual/memory-aware languages
   will also suffice.
 - at least a year of experience of using linux systems.
* A note about writting skills
** Spelling
So I'm going to be honest here. I'm bad at english spelling. Like
/really/ bad. I'm nearly certain I have Dysgraphia outside of an
official diagnosis, although funny enough when I was in Austria my
german spelling skills were normal.

Regardless, I am going to be typing 90% of this manual in an editor
with no spell-checking. I'll only go through and have someone else
edit it when it's done.

I'm not saying this as an excuse for someone to have bad spelling. I'm
saying this so I can avoid getting hundreds of emails of people
pointing out my misspellings. I know. If you read it, and you
understood it: then my job is done. You can be a picky imperical
englishman to the person who will eventually edit this.
** 2nd-Person
I like to make all my technical writtings Feynman-style (an idol of
mine). As you've already seen, I will write this as if /I'm/ talking
to /you/, as if its a discussion between /us/, as if /we/ are working
side by side.

Its worth noting that Feynman didn't make physics. But I did make
OidaDB. So a lot of information is perscribed by my perspective.
