* this file
Here i shall type a buisness model following the standard business
canvas.

I'm not completely sure why I need to do this. It may end up just
another forgotten document. But I need to get this done with and
thought about otherwise I'm putting in all of this effort in making
another database for nothing.


Tangigbla value: have profit.

stagetic value: be so big and be so free that someone eventually
buys us out.

Either way. Value is value. The more the better. Don't over think it.


Let us explore.

/Note to self: don't google anything just yet. Don't search for/
/existing answers, they will come to me as they need be. Like/
/everything in this project its best I know the answer to the question/
/before I ask it./

* Realistic Value

We have a database tech, so what? Who would use it. Why would they use
it? If I'm enterprise rent a car, why should I switch to this shit?

 - Its faster
 - Its modern
 - Its more practicle
 - Your team will like it
 - Its timeless
 - It'll save on hosting due to the lack of nodes needed.
 - More redundant
 - /its just better/ ... eh... gross argument.

The only real value is that its different and its run by me. rather
thats a good thing or a bad thing.

So who am I?

 - Tech experience in sensitive data
 - Experiance in big data
 - Passion for efficient software
 - Passion for massive systems
 - Passion for delegation and organization
 - Passion for simplicity

** Some other ideas:

 - Clients shall be given a representative for support
 - Not just any person can have the technology. The object code will
   remain secret. If the object code is leaked, all of it shall be
   marked with who's object code it was... hmmm... very stingy. Hard
   sell too. We'd have to sell *comprehendsive support* if I wanted
   something like that. hmmmm... doubt it.
 - *need a fucking dashboard*. A database WITH a pre-built
   dashboard. That's sexy.

* Potential value

This technology will attract people to use it in their underlining
veins of information. If they adopt it, they're very much in bed with
us. Which is a double edge sword... proper CTO/CIOs will be protective
about making such a move. They need to trust the product.

 - *Leave little unknown* for potential customers.

Now that they can trust us, they must adopt it. That makes CTOs and
CIOs sweat. No one wants to worry about that shit. But here's the
thing, the technology itself is not a business. But a business can
sell the service of helping migrate.

This is a good idea. Sense most developers know all other (open
source) technology, it's easy to move out of most modern databases.

 - *License the product, sell the migration*

I would even license selling rights to other companies who'd want to
also help their clients migrate.

Thus, I want a holding company, which doesn't really make money on its
own until it licenses the technology to distributers whom can sell it
to their clients. They can always fire the migraters/support... but
they can't push away their product.

On this note of profiteering, another cheeky thing to do is 

 - *Sell the hosting*

... set up the hardware for them and make sure they have a API and
control panel they can use. Hosting fees are wonderful. If they want
to host it in house, then make sure to charge extra for the lost of
profit in the hardware.

* Costs
** Payroll
Payroll and marketing. But what will the alocation of such look like?
whats importatn? In my the order in my head:

 1. R&D (they give Support the answers)
 2. Support (They can tell what marketing to say, they know the pain the best)
 3. Marketing
 4. Administrative

For a perfect /startup/ I would need the following:

 - CEO: Someone with experiance to run the company. Someone who
   understands the product comes before the customer. It can be
   me. But my time would be better used as a CTO. If it must be me
   then I'm going to need a damn good CTO.
 - CTO: Me.
 - CFO: Brett. Or someone like Warren Fischer: a man with no emotions,
   just numbers and honesty.
 - COO: In charge of support/adminsitrative/project
   management. Someone who I can count on to make sure everyone is
   coming to work and doing their job with a proper sense of
   accountability. I want someone a "sympathetic asshole".
 - Director of Marketing: Someone who knows how to reach people and
   get us famous. *Not needed: not big enough*.
 - Director of Revenue: Someone who can execute profitable ideas and
   has a perfect sense of risk assesment. Someone who is always
   looking at our numbers and working with the CFO to make good
   desicions on price tags. They can work in sales.
 - Sales Officer/Account Manager: A salesperson. But such a good one
   they're responsible for the other sales team. Someone who can be
   bitched at about our shitty figures and will answer back the
   difficulties of sales and propose solutions to any problems. I
   don't want a yes man, in fact, I want a no man.
 - Salesman x2. Someone who can follow the Sales officer off the face
   of the earth. They don't need to be experianced. Just good enough
   to love the challenge of the job.
 - Developer x2. Good developers who I will like. Who are critical
   about every line of code they write. Someone who doesn't b-line a
   fix but debates with all the possible solutions. Someone who shares
   the same passions about me. I don't want noobies. Will work in
   support mainly.

Given the project is in beta, I think 2 years of said team is enough
run way. 

Per year:

 - 200k CEO
 - 100k CTO
 - 100k CFO
 - 80k DoM
 - 100k DoR
 - 70k (+comission) Sales Officer
 - 120k (+commission) Sales x2
 - 190k (+commission) Dev x2
 - 860k Total

** Consultants/other

 - 20k - marketing materials
 - 12k - facility
 - 4k - servers
 - 5k - Misc expenses

** In total

910k/year

1.820m "perfect" investment for 2 years run time. After that we must
pull about 1m in sales per year to stay afloat.
* Income
 - Licensing the product
 - Leasing (subleasing?) hardware
 - Support services
 - Licensing specific versions of the product (plan A, B, C...)

hmmm... lets put them in the order of what I consider most important.

 1. Leasing hardware (initially a lot of overhead)
 2. Support services (also good because it allows us to obtain great
    industry knowlege with many customers.)
 3. Licensing

** Leasing hardware: potential AND realistic value.

Obviously leasing hardware gives us profit. And if we use a 3rd party
provider to technically "sublease" hardware, its hard for us to loose
any money. Instant profit and thus good realistic value.

However, there's potential value here too, infact a lot. If we
sublease out 500 customers, we can eventually buy our own hardware nad
switch those same 500 customers to servers we own, cutting out the
middle man. We can do that without those customers even knowing. We
cut huge costs overnight and no one will notice. We can only do this
with many millions of dollars though. But this fact alone is value.

This can also mean we can use the strategic value to justify losing
money on the subleasing program for the eventual returnn of switching
to in-house.


* Monologue
I speak to myself now. As if I'm talking to someone else to hype up
the product. this is a much needed excersise. thus i justify my
product, thus i deam its existance. hense i cease the fire of doubt
within me and my opponenets of this products nessecity. this recalls
me of the flycatcher fleet.

the secrent to justification is to take why /i/ can justify it and
project it on others. another way reminds me of my goonwaffe campaing,
don't say "probably", "might", "should"... say "will". Talk in the
perfect futre/present tense. talk like you're already the winner but
without the tribute of truth. Make words as serious as the product,
and the legitmacy shall spread.



*People need this technology.* With it they will develop technology
that will run faster and more true than it ever has. I would guess
that nearly all/90% of all information on earth are stored in
databases, shared between MySQL, MSSQL, Oracle, MongoDB, and
Postgres. 5 Products for that much information? It's about to be 6 and
ours will be the most modern.

The biggest in the enterprise sector are MongoDB and Oracle becuase
they provide support. We will also provide support. We're going to up
there with them. Between them is 10 billion dollars of revenue. Making
just a slightly cheaper, slightly faster product and support will
quickly conqure that 10b so long we have transition scripts.

* Venture Capitalist
Based on their previous protfolio having database technology, the
following firms are to be considered:

 - https://www.intelcapital.com/contact/
 - https://www.iqt.org/contact-us/ (CIA/Government investor, went for mongodb)
 - https://www.flybridge.com/ (like pre-seeding)
 - https://www.nea.com/contact
 - https://www.usv.com/people/
 - https://www.sequoiacap.com/


* See also
 - https://hazard.typepad.com/hazard-lights/2012/03/developer-driven-business-models.html
