* DOCUMENTATION:

The most important things bout the edbl.h namespace is the content of
this comment you're reading now. It is imporant you read this comment
and undestand it before you start fucking with the below functions in
anyway.

Firstly, these functions are just wrappers of fcntl(2)... so read up
on that regarding advisory locks. And note that these functions are
just kinda stupid.  The functions don't help you do your work, this
comment does. So enough with the introduction, lets begin.

It is VITAL that you lock the right things in the right order. Not
locking things in the right order WILL result in deadlocks and
headaches.

So, to get the proper order of which to lock things require to know
what job you're trying to do. The first variable to this is the
element type:

 - Entry
 - Structure
 - Objects

Next, what cateogyr of operations are you trying to perform?

 - Create
 - Read
 - Update
 - Delete
 - (defragging will be discussed below)

|          | *Entry*     | *Structure*                  | *Object*             |
| *Create* | entry mutex | structure mutex              | same as update       |
| *Read*   | /no action/ | /no action/                  | clutch off, sh locks |
| *Update* | clutch on   | /not possible/               | clutch off, xl locks |
| *Delete* | clutch on   | clutches on, structure mutex | clutch off, xl locks |


* Entry
** XL Clutch Lock
 1. put a XL lock on the first byte (clutch lock)
 2. put a XL lock on the second byte.
 3. remove XL lock from the first byte
 4. Do whatever you need to do with the lock
 5. release the lock from the second byte.
** SH Clutch Lock
 1. put a SH lock on the first byte (clutch lock)
 2. put a SH lock on the second byte.
 3. remove SH lock from the first byte
 4. Do whatever you need to do with the lock
 5. release the lock from the second byte.
** Entry-Creating
  1. Lock the entry-creation mutex
  2. Surf the index for an EDB_TNONE entry.
  3. Place an XL clutch lock on that entry.
  4. Set the type to EDB_TPEND to deter other creation attemps.
  5. Unlock the entry-creation mutex
  6. Whiest retaining the XL clutch lock, make whatever edits are
     needed to the entry and chapter.
  7. Set the type to whatever it needs to be. This is the final
     marker to indicate a non-corrupted entry. if there's a crash
  8. Release the XL clutch lock.
** Entry-Deleting
  1. Place an XL clutch lock on that entry.
  2. Whiest retaining the XL clutch lock, make whatever edits are
     needed to the entry and chapter. DO NOT TOUCH ITS TYPE yet.
  3. Lock the entry-creation mutex
  4. Set the type to EDB_TNONE
  5. Release the XL clutch lock.
  6. Unlock the entry-creation mutex
** Entry-Writting
  1. Place an XL clutch lock on the entry you wish to create.
  2. Whiest retaining the XL clutch lock, make whatever edits are
     needed to the entry and chapter.
  3. Release the XL clutch lock.
** Entry-Reading
  1. Make sure the entry doesn't have a clutch lock
  2. At this point, if you'd like to confidently pull in structure
     information, you can do it here.

* Structure
** Structure-Deleting
You must lock the entry creation mutex so nothing can be created
with the structure you're trying to delete.

You must go through all indexes, placing sh clutch locks on each one,
then make sure it doesn't posses that structure. If it does, then
that's an error, you cannot delete the structure, roll back the locks
and quit.

* Object
** Object-Reading

  1. Read the relevant entry, make sure it exist ([[Entry-Reading]]), keep
     the SH lock on the entry.
  2. With the lookup root page id in hand:
     - SH Lock on the first byte of page
     - Load the page
     - Get the ID of the next page
     - deload page
     - Remove SH lock on first byte
     - Do this recusively until you get the leaf ID
  3. With the leaf ID:
     - Place a SH lock on the object
     - load the page, copy the data
     - Remove SH lock
  4. Finally, remove the SH lock on the entry.

** Object-Updating

  1. For the look up, do the same process as writting as
     [[Object-Reading]] steps 1-2.
     - (todo: Object-Creating) *However*, if a new node of the B-tree must be created, upgrade
       the lock from an SH to an XL lock on the first byte of the node
       that needs to be modified. Then check again to see if it hasn't
       been modified already, thenm modify it if it hasent, then
       remove the lock and continue as normally. This is to remove the
       possiblity of 2 jobs accidentally adding the same new page
       twice.
     - (note to self: upgrading locks is bad, however sense its
       1-lock-per-operation in terms of pages, we arn't dealing with
       multiple recursive locks thus leads to it being impossible to
       dead lock from upgrades)
  2. With the leaf ID:
     - Place an XL lock on the object
     - load the page, edit the data
     - remove the XL lock.
  3. Remove SH lock from entry.

** Object-Creating
*** Auto ID Creation
  1. Place an SH clutch lock on the entry (thus same as [[Object-Reading]]
     step 1)

  2. Place an XL lock on the entry's trashlast field.

  3. If the trashlast page is 0. Tne this means more pages are needed
     to be created. See [[Object-Creating-Lookup]].

  4. With the trashlast page id, before you load that page, you must
     place a XL lock on the 'trashstart_off' field in the page's
     header.

  5. With the trashlast page loaded, handle all trash faults by:
     - Updating trashlast with the page loaded's trashvor.
     - unloading the page loaded. then releasing trashstart_off lock.
     - repeat step 4-5 until there's no more trash faults or,
       trashlast ends up being 0. In the latter case, go to step 3.

  6. Release the XL lock on the entry's trashlast field.

  4. Place an XL lock on the trash record you wish to modify, then
     update trashstart_off with the next step in the linked list.

  5. Once trashstart_off is updated, release the XL lock on it but
     keep the XL lock on the record.

  6. Do the creating of the record and what not. (If a user flag
     prevents its creation, simply skip this step. Note how what we've
     just done is taken out this record from the trash yet not
     successfully un-trash it. This is actually fine, sense trash
     records must be able to be untrashed that would me this record is
     unfit to be trash. The user would have to manually create this
     with proper flags.)
  7. Release the XL lock from the record.
  8. Release the SH clutch lock on the entry.

*** Object-Creating-Lookup
Note the only time you should be here is from auto-id creation. Thus,
their should be an SH clutch lock on the entry and an XL lock on the
trashlast field. So lets continue with the lookup root

 1. With the lookup page, put an XL lock on the *second* byte of the
    page.
    - The reason why we don't put an XL lock on the first byte is
      because lookups should still be able to happen (via
      Object-Reading/Object-Writing). But with this XL lock the only
      thing we seek to block are other attempts to modify the lookup
      pages.
 2. load the page
 3. navigate to the first null-reference
  
* Defraging

Notes: PAGE-BASED CLUTCH LOCKS DONT WORK, a dead lock can happen
unless we guarentee that all pages per-entry are in order. Entry based
clutch locks are faster, easier, and defragging is rare so their
interuption-capabilities are worth it.

 1. go through all the pages and put a clutch lock on all relevant
    entries. it is important that you put the clutch locks on in
    accending order of 

hmmmmmm... why don't just put clutch locks in each page header? and
then put a massive lock over the whole range? the header lock will be
the clutch and when there's no more locks being placed the large lock
will be installed... BUT: we must test to make sure that all the
smaller clutch locks will be consolidated into the large lock (note
that all locks are installed via the same discriptor).

 2. Place an xl lock over the entire area and wait
 3. Once the lock is obtained 
